name: CI Gate

on:
  pull_request:
  push:

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Framework Integration
        run: |
          python autonomous-framework-v2.py quick_assessment

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Pytest smoke (health endpoints)
        run: |
          pytest -q backend/tests/test_health.py
      - name: Run CI Gate (strict)
        env:
          CI_STRICT: '1'
        run: |
          node -v
          npm run ci:gate --silent
      - name: Generate remediation plan
        if: always()
        run: npm run remediate --silent

