name: Frontend CI

on:
  push:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'vite.config.ts'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'vite.config.ts'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm install eslint --no-save
      - run: npm run build
      - run: npm test -- --run
      - run: npx eslint . --ext .ts,.tsx
      - run: npx tsc --noEmit
